name: Hello World
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from my new repo!"
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test file created by the workflow." >  test.txt
      - run: cat test.txt
  list-files:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la