name: matrix strategy
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [1.0, 2.0]
        env: [dev, prod]
        exclude:
          - os: windows-latest
            
    steps:
      - run: echo "This is a job running on ${{ matrix.os }} with version ${{ matrix.version }} in ${{ matrix.env }} environment."