name: Running multiple runners jobs
on: push

jobs:
    runner1:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "This is runner 1" 
                cat /etc/os-release   
    runner2:  
        runs-on: windows-latest
        steps:
            - run: |
                echo "This is runner 2"
                systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    runner3:
        
        runs-on: macos-latest
        steps:
            - run: |
                echo "This is runner 3"
                sw_vers | grep "ProductName\|ProductVersion"